config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products= Product.all		
	end

	def new
		@product = 	Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy
		redirect_to products_path
	end

	def create
		product = Product.new(product_params)
		if product.save
			redirect_to products_path
		else
		end
	end

	def update
		product = Product.find(params[:id])
		product.category_ids.each{|x| product.categories.delete(x)}
		product.update(product_params)
		redirect_to products_path

		end

	def noesta(arr1,arr2)
	# metodo que permite sacar los elementos que no estan contenidos 
	# en el arreglo 2 y si en el arreglo 1

	# arr1=[1,2,3,4,5,6]
	# arr2=[2,4,6,8,10,12]
	# noesta(arr1,arr2) =>  [1,3,5]
	# noesta(arr2,arr1) =>  [8,10,12]
	#
	arr1.map!{|x| x.to_i}
	arr2.map!{|x| x.to_i}
	arr1.reduce([]){  |accu,element|

	 if arr2.include? element.to_i
		accu    
	 else
		accu<< element
	 end

	}
end

	private

	def product_params
		params.require(:product).permit(:name,:price,category_ids:[])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_formproduct.html.erb
<%= form_for @product  do |f| %>
<div class="form-group">
	<%= f.label "Nombre:" %>
    <%= f.text_field :name, class: "form-control"%>		
</div>
<div class="form-group">
	<%= f.label "Precio:" %>
    <%= f.text_field :price, class: "form-control"%>		
</div>
<div class="form-group">
  <%= f.label "Area of Categories" %><br />
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
</div>
	<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Form for Edit Product</h1>
<%= render 'formproduct'%>

app/views/products/index.html.erb
<h1>Productos</h1>
<%= link_to "Nuevo Producto",new_product_url %>
<table>
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Categorias</th>
    <th></th>
  </tr>
  	<% @products.each do |product|%>
  	<tr>
		<td><%=product.name%></td>
		<td><%=product.price%></td>
		<td> <% product.categories.each do |category|%>
			<%= category.name %>
			<% end %>
		</td>
		<td><%= link_to "Editar", edit_product_path(product)%>
			<%= link_to "Eliminar", product , method: :delete%>
		</td>
	<tr>
	<%end%>

</table>

app/views/products/new.html.erb
<h1>Form for new Product</h1>
<%= render 'formproduct'%>